development:
  adapter: postgresql
  encoding: unicode
  database: todo_app_development
  host: localhost
  username: Elliot
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: todo_app_test
  host: localhost
  username: Elliot
  port: 5432

